### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by BLANK-MOJO** [saltedfish666/dazhongdianping#2]
Traceback (most recent call last):
  File "F:/Downloads/dazhongdianping-master/dzdp.py", line 98, in <module>
    css_content = get_css_content(res.text, headers)
  File "F:/Downloads/dazhongdianping-master/dzdp.py", line 29, in get_css_content
    css_link = 'http:' + css_l.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by BLANK-MOJO** [comment]
把css_l 和 svg_l 重新用re.findall 写了一下搞定了，感谢老铁
